package com.sky2dev.day17.model;

public enum AlarmType {
    INTERFACE_DOWN,
    HIGH_TEMPERATURE,
    HIGH_CPU_USAGE,
    MEMORY_EXHAUSTION,
    POWER_SUPPLY_FAILURE,
    SIGNAL_STRENGTH_LOW,
    CARRIER_UNLOCK,
    BER_HIGH,
    EBNO_LOW,
    BUC_FAILURE,
    LNB_FAILURE,
    DEVICE_UNREACHABLE,
    DATABASE_DOWN,
    APPLICATION_DOWN
}
