apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: day26-mysql-pvc
  namespace: day26-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: day26-mysql-pv
