apiVersion: v1
kind: ResourceQuota
metadata:
  name: day26-resource-quota
  namespace: day26-platform
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "2"
