apiVersion: v1
kind: Secret
metadata:
  name: day26-secret
  namespace: day26-platform
stringData:
  MYSQL_USERNAME: day26
  MYSQL_PASSWORD: day26pass
  SPRING_DATASOURCE_USERNAME: day26
  SPRING_DATASOURCE_PASSWORD: day26pass
type: Opaque
