spring:
  application:
    name: day17-alarm-monitoring-systems
  datasource:
    url: jdbc:h2:mem:day17db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
