spring:
  application:
    name: day18-hub-monitoring-and-control-systems
  datasource:
    url: jdbc:h2:mem:day18db;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084
